README.md

Add travis build badge to readme

---

src/gm3/components/measure.jsx
src/gm3/util.js

Add chains to linear measurement units.

---

CONTRIBUTORS.md
docs/style_guide.md

1. Updated CSS style guide.
2. Added contributors file is disclaimer/waiver type header.

Docs writing

---

Gruntfile.js
src/tasks/grunt-less-linter.js

1. Added new custom less lint checker.
Only really cared about keeping out tabs an ID selectors which
were small rules to write.
2. Added configuration to the Gruntfile including adding lesslint
to the standard linting process.

Add LESS linting utility to the grunt checker.

---

demo/test.js
package.json
src/gm3/application.jsx
src/gm3/components/modal.jsx
src/gm3/components/modals/alert.jsx
src/less/modal.less
tests/gm3/components/modal.test.jsx

1. The "Modal" component is a base class upon which other Modal dialogs can be based.
2.  Wrote an example "Alter" modal dialog as a sub-classed component.  
3. Added "API" hooks for dialogs in Application.
4. Wrote a test to prove the modal dialog works.
5. Fixed some versioning problems that prevented the test suite from properly running.
This branch will help get printing moving along.

Modal Dialog Components

---

demo/test.html

So it can work outside the webpack-server/docker environment.

Use relative paths in demo/test.html

---

src/gm3/components/serviceInputs/length.jsx
src/gm3/components/serviceManager.jsx
src/gm3/util.js

Adds a Length service input type per issue #9 
* Does the select input need an ID field? What do we use the ID field for?

Length Service Input

---

examples/desktop/debug.html
examples/desktop/index.html
examples/mobile/index.html
webpack.config.js

When packaging this lets us keep geomoose up a level
so it is shared by multiple applications. This demonstrates:
1. That GM is really more a library.
2. Allows each folder to evolve into separate repo's,
one for the "library" and one for the "application."

Moved geomoose "up" on dir for examples.

---

examples/desktop/app.js
examples/desktop/debug.html
examples/desktop/index.html

Accounts for @CaitW's changes and puts the OSM geocoder as the default geocoder.

Set the OSM geocoder to be the default service.

---

examples/desktop/mapbook.xml
src/gm3/actions/catalog.js
src/gm3/components/catalog.jsx
src/gm3/components/catalog/tools/download.jsx
src/less/catalog.less

Layers can now be downloaded as GeoJSON or KML when
configured for the download tool.

Download tool!

---

examples/desktop/mapbook.xml
src/gm3/actions/catalog.js

Added "draw-line" tool to the sketches layer.

Add missing draw-line tool to sketch layer.

---

src/gm3/components/serviceManager.jsx

Add loading affordance to service manager

---

src/gm3/components/serviceInputs/select.jsx
src/less/serviceForms.less

The service forms have been bugging me and this cleans
up the display quite a bit.  The inputs now look a bit
more "bootstrappy" style where they're wide and big.

Small styling changes for service forms.

---

src/gm3/components/serviceManager.jsx
src/services/select.js

What it says on the tin.  Addresses issue #77

Added select feature to select.

---

src/gm3/reducers/mapSource.js

Fix for invalid map-sources being turned on.

---

src/gm3/components/map.jsx

Ensures the extent is properly processed.

Fix for broken zoom-to icons, refs: #96

---

examples/desktop/app.css
examples/desktop/app.js
examples/desktop/index.html
src/gm3/components/jumpToExtent.jsx
src/index.js

Allows users to zoom to user-defined bounds
```Javascript
app.add(gm3.components.JumpToExtent, 'jump-to-extent', {
locations:  [
{
label: 'Parcel Boundaries',
extent: [-10384071.6,5538681.6,-10356783.6,5563600.1]
}
]
});
```

Jump to Extent 

---

src/gm3/components/map.jsx
src/gm3/components/serviceInputs/length.jsx
src/gm3/components/serviceManager.jsx
src/gm3/jsts.js

1. Fixed quirks with the buffer input.  
a. The buffer "live update" now works more closely with the state.
b. That distance updates properly.
2. Fixed issue with multi-point/multi-geometry selections.  They are now buffered then unioned.

Fixing Buffering Quirks

---

examples/desktop/app.js

After merging in AGS the default select options
were a little scrambled. My bad.

Fix for default selection options.

---

src/gm3/components/map.jsx
src/gm3/components/serviceManager.jsx

1. Handled the measure tool special case more smoothly.
2. Fixed the state-test for the map component.
Refs: #112

Tweaks to prevent the tools from dead ending.

---

src/gm3/components/map.jsx

This was causing a litany of bugs.
refs: #84

Turn off multi-select.

---

src/gm3/util.js
src/services/findme.js
tests/gm3/util.test.js

1. Added the ability to reproject features to util.
2. Fixed FindMe to use that fucntionality to properly
handle the return from navigator.
refs: #129

Service and API code changes for FindMe.

---

examples/desktop/mapbook.xml
src/gm3/actions/catalog.js
src/gm3/components/catalog.jsx
src/less/catalog.less

Return of the metadata tool!

---

src/services/select.js

The user now receives a prompt when they have not drawn
a geometry for select.
refs: #83

Selection service now alerts user with no geometry

---

examples/desktop/app.js
src/gm3/components/coordinates.jsx
src/gm3/components/measure.jsx
src/gm3/components/serviceManager.jsx
src/less/coordinates.less

1. Fixed the measurement of points.
2. Added a "sum" line for measurement of lines.
refs: #85

Measure tool fixes for points + line summary.

---

src/gm3/application.jsx
src/gm3/trackers/hash.js

This implementaiton uses a "param" of "always-on",
this will let administrators specify their own layers
as never being able to be turned off.
Refs: #89

Add support for `always-on` layer.

---

package.json
src/gm3/application.jsx
src/gm3/components/toolbar.jsx
src/services/findme.js
src/services/geocode-bing.js
src/services/geocode-osm.js
src/services/identify.js
src/services/search.js
src/services/select.js
src/services/zoomto.js
tests/app.test.js
tests/gm3/application.test.js
tests/gm3/components/coordinates.test.jsx
tests/gm3/components/toolbar.test.js
tests/gm3/jsts.test.js
tests/gm3/reducers/ui.test.js
webpack.config.js

Major push to get more tests integrated into the UI.

More coverage

---

package.json

Fixes regression in 33f33061, PR #141

Fix tests on Windows (again).

---

src/services/geocode-osm.js

No more major bugs and the points from the search results
will now render on the highlight layer.

Updated OSM geocoder.

---

src/gm3/components/map.jsx
tests/gm3/components/map.test.jsx
tests/gm3/reducers/map.test.js

1. Added explicit tests for the map reducer.
2. Added a test for the map component.  While far from complete it does help to ensure basics will not cause errors.

Added EVEN MORE tests.

---

src/gm3/components/layers/xyz.js
src/services/geocode-osm.js

1. Added `crossOrigin` tweaks for XYZ layers.
2. Fixed http vs https issue for osm geocoder.

Fix some https/access-control bugs.

---

examples/desktop/debug.html
examples/desktop/index.html

fix for encoding warning

---

docs/ms4w-quickstart/index.md

I've verified this and it all seems to be working pretty well.

Added demo-data reference.

---

examples/desktop/mapbook.xml

Added HTML legend linking to OSM (c).

---

Gruntfile.js
docs/howto/disclaimer.md
docs/howto/index.md
webpack.config.js

We don't need no stinkin' extension this time!!!
refs: #159

Document how to do a Disclaimer in GM3

---

examples/desktop/mapbook.xml

Updated the styling to be less ... gross and opaque.
@elil I was able to fix this without going "upstream".  It just requires a little different syntax.

Fix for the "Eli Bug"

---

src/gm3/components/favorites.jsx
src/gm3/components/print/printModal.jsx
src/gm3/components/serviceManager.jsx
src/gm3/components/visibleLayers.jsx
src/less/gm3.less

1. Added messages to the Visible and Favorites tabs
explaining what they are.
2. Used the new "info-box" style for the info during the empty
super tab.
3. Added help text to the print dialog for when there are
unprintable layers.

Adding more helpful text.

---

examples/desktop/mapbook.xml

Buries the USGS layers a little bit to make the demo look less broken refs: #160

Commenting out the usgs layers with a warning.

---

docs/index.md
docs/templates.md

1. Added the instructions on templates.
2. Added an index to the docs directory.

Templating information.

---

docs/howto/index.md
docs/howto/style-the-header.md
examples/desktop/debug.html
examples/desktop/index.html
examples/desktop/mapbook.xml
webpack-deploy.config.js

How to style the header.

---

docs/howto/index.md
docs/howto/style-the-toolbar.md
src/gm3/components/toolbar.jsx

1. New doc covers all the CSS tweaks available for the toolbar.
2. Found that tools didn't have a title making them very difficult
to use when there are no labels.

Updated docs for how to tweak the toolbar.

---

examples/mobile/index.html
examples/mobile/mapbook.xml
examples/mobile/mobile.js

Fixed the mobile to , ya know, work.

Updated mobile app.

---

docs/actions-and-services.md
docs/index.md
docs/input-types.md
src/services/findme.js
src/services/geocode-osm.js
src/services/select.js

Some minor spelling fixes in comments and two new docs!

service and actions docs

---

src/gm3/components/layers/vector.js
src/gm3/components/map.jsx

Added <map-source type="geojson"> which will directly
download a geojson from the specified <url>.

Add support for direct GeoJSON type map-sources

---

docs/howto/add-search.md
docs/howto/configure-measure-tool.md
docs/howto/disclaimer.md
docs/howto/index.md
docs/howto/print-layouts.md
docs/howto/style-the-header.md
docs/howto/style-the-toolbar.md

how-to's were inconsistently titles, this has been remedied.

fixed titles

---

src/gm3/components/catalog.jsx

Looks like this got missed in f86ebea.
refs: #201

Fix display of metadata icon.

---

examples/desktop/mapbook.xml
examples/mobile/mapbook.xml

Catalog no longer support the multiple tag in groups.

dropped "multiple=true" from the mapbooks

---

package.json
src/less/catalog.less
src/less/icons.less

1. Made them bigger
2. Made the spacing wider
3. Put all the FA overrides into one declaration.

Made catalog icons more touch friendly.

---

src/gm3/application.jsx
src/gm3/components/catalog/tools/download.jsx

This ensures that if a layer happens to have a particular
filter, then it can be downloaded.

Filters are now honoured for download features

---

docs/howto/add-search.md

Fixed search typo (missing -wfs).

---

src/gm3/components/catalog/tools/upload.jsx

Added check for invalid coordinates.

---

examples/desktop/app.css

This is an issue that makes itself readily visible in FF on linux.

CSS tweak to prevent the footer from overflowing.

---

src/gm3/components/layers/wms.js
tests/gm3/components/layers/wms.test.js

Fix for extra "?" in URL.

---

examples/desktop/app.js
src/gm3/components/coordinates.jsx

Fix for coordinate display order.

---

src/gm3/components/print/geopdf.js
src/gm3/components/print/printModal.jsx

World's First Javascript + GeoPDF maker.

---

docs/howto/index.md
docs/howto/query-as-vector.md

Actually documented query-as!
refs: #245

create docs for query-as.

---

examples/desktop/debug.html
examples/desktop/index.html
examples/mobile/index.html

Fixing up html-encoding issues.

---

examples/desktop/app.css
examples/desktop/debug.html
examples/desktop/index.html
examples/desktop/tabs.css
examples/desktop/tabs.js

It's not the prettiest but gets the job done.

Added a tab toggler.

---

src/gm3/actions/map.js
src/gm3/application.jsx
src/gm3/components/map.jsx
src/gm3/components/serviceManager.jsx
src/gm3/reducers/query.js
src/less/serviceForms.less
src/services/identify.js
src/services/search.js
src/services/select.js

MapServer returns WFS exceptions as HTTP status code 200,
this prevents the standard error detection from working. The code has
been updated to handle ows:Excpetion and wfs:Exception errors properly
and delivers them to the user.
refs: #254

Added error handling for WFS requests.

---

examples/desktop/mapbook.xml
src/gm3/components/layers/bing.js

Add the ability to specify other Bing layers.  Included examples in the mapbook.xml/

Allow any bing layer name

---

examples/desktop/tabs.css

or more consistent with look of other icons...

Make the tab toggler prettier

---

src/gm3/components/grid.jsx
src/gm3/components/map.jsx
src/gm3/components/serviceManager.jsx

1. Checks to ensure a geometry exists and that it is valid for identify.
2. Creates a better failure notificaiton.
3. Add undefined check for the grid-columns.
refs: #288

Fix invalid geometry for identify.

---

package-lock.json
src/gm3/components/map.jsx

Too many deep deps getting wonky. This has become, unfortunately,
necessary.

Add lock file to prevent mis-versioned builds

---

webpack-deploy.config.js
webpack.config.js

Adds back in babel-polyfills to the build profiles.

Fix for IE11 bugs

---

.gitignore
selenium/local-runner.py
selenium/requirements.txt
selenium/runner.py
selenium/tests/__init__.py
selenium/tests/basic.py

This is meant to be a _very basic_ smoke test
to ensure that IE will load the application without
error.

Adding selenium tests for browser stack.

---

src/gm3/actions/catalog.js
src/gm3/actions/mapSource.js
src/gm3/application.js
src/gm3/components/grid.js
src/gm3/components/map.js
src/gm3/components/serviceForm.js
src/gm3/components/serviceInputs/buffer.js
src/gm3/components/serviceInputs/layersList.js
src/gm3/components/serviceManager.js
src/services/identify.js

- Giant pile of React/Redux fixes
- Fixes the broken identify.
Refs: #323

Fix for Identify

---

src/gm3/components/coordinate-display.js
src/gm3/components/coordinates.js

USNG coordinate precision

---

src/gm3/components/serviceManager.js

Restores the service-manager parent class.

Fix for broken service styles

---

.travis.yml
LICENSE
install_test_deps.sh
package-lock.json
package.json
src/gm3/components/layers/wfs.js
src/gm3/components/map.js
tests/gm3/components/layers/wfs.test.js
tests/setup.js

Refactored WFS filter building code to support
OR-type queries.
Even with tests!

Added support for OR operator in queries (and travis fixes)

---

docs/ms4w-quickstart/index.md

1. FIxed MS4W download links.
2. This also needs merged to fix some documentation errors:
- https://github.com/geomoose/gm3-demo-data/pull/2

Updating broken docs

---

docs/ms4w-quickstart/index.md

- fixed MS4W download link
- modified wording for the manual GeoMoose install

minor wording change for MS4W-Quickstart

---

examples/desktop/mapbook.xml
examples/mobile/mapbook.xml

Changes to both mapbooks.
refs: #306

Drop Arc version from mapbooks.

---

src/gm3/components/serviceManager.js

onServiceFinished dispatch prop was missing
from the serviceManager class.
refs: #385

Fix the close button

---

eslint.config.js
src/gm3/components/coordinate-display.js
src/gm3/components/map.js

* These should not have made it into master!
* Add parser rule to prevent console.logs in the future.

Clean-up console.logs

---

src/gm3/components/serviceForm.js
src/gm3/components/serviceManager.js

Found a beter fix for the form state management bugs.
refs: #373

Better fix for service form values

---

src/gm3/components/visibleLayers.js
src/less/catalog.less
src/less/serviceForms.less

Fixed spelling, added padding.

---

docs/howto/add-attribution.md
docs/howto/index.md
examples/desktop/mapbook.xml
src/gm3/actions/mapSource.js
src/gm3/components/attribution-display.js
src/gm3/components/map.js
src/less/attribution-display.less
src/less/gm3.less

Adds a new `<Attribution>` element to the `<map-source><layer>` element.

Put attribution on map

---

docs/howto/configure-select-options.md

Gives info about how to change the default select settings. Let me know if there's anything else I can add or anything that can be refined.
refs: #408

Adding Select docs

---

examples/desktop/app.css
examples/desktop/debug.html
examples/desktop/index.html
examples/desktop/tabs.css

The old tab toggler ate up some real-estate and
the tabs never really shut. This is an improved
version with a little animation and floats above
both the map and tabs.

Improved tab toggler

---

examples/mobile/mapbook.xml

I'm pretty sure these are all the old scalebars, so should be deleted from the demo mobile Mapbook...

Remove catalog sources for old MapServer scalebars

---

.travis.yml

Update Travis to Node 10

---

docs/howto/index.md

Added select options config link to index.md

Updated index to include doc for modifying select options

---

package-lock.json
package.json

1. Changes the package name to @geomoose/gm3
2. Removes downloading dev-only packages. Since we distribute a `dist`
directory, there is no need to also download all the dev deps.

Updated Package.json for publishing

---

src/gm3/application.js
src/gm3/components/layers/vector.js
src/gm3/components/map.js
src/gm3/components/serviceForm.js
src/less/results.less
tests/gm3/components/map.test.js

This is a general housekeeping PR.
1. The CSS is a small layout bug I found while working on a real app.
2. The removal of util.xhr is to make when we use JSONP
more explicit.
3. Updated the map tests to, you know, pass.

Fixes tests, remove use of util.xhr, small CSS update

---

docs/howto/add-zoom-jumper.md
docs/howto/configure-scaleline.md
src/gm3/components/jump-to-zoom.js
src/gm3/components/map.js
src/gm3/reducers/map.js
src/less/gm3.less
src/less/map.less

- Includes the new jump-to-zoom control
- Include docs for above + docs for configuring the scaleline
- Adds a new less file for the map.
refs: #50

Add Zoom Jumper

---

src/gm3/components/print/printModal.js

Using the "refs" is both evil and broken. This changes that.
refs: #421

Fix state management issues with print dialog

---

examples/mobile/index.html

Use geomoose.min.js instead of geomoose.js in mobile example.

mobile: Use geomoose.min.js

---

src/gm3/components/modal.js
src/gm3/components/print/printModal.js
src/gm3/components/print/printPreviewImage.js

Adds additional CSS support to the Modal's render body method.

Fix print preview image being buried

---

src/gm3/application.js
src/gm3/components/serviceManager.js
src/gm3/components/toolbar/button.js
src/gm3/components/toolbar/index.js
tests/gm3/components/toolbar.test.js

Pushes the state management to the tool actually starting.

Better fix for the state management of draw tools

---

docs/howto/configure-select-options.md

Gives additional guidance about how to further configure select options without causing additional errors

Update selection options doc

---

src/gm3/components/serviceForm.js

Centalizes submit logic in service form for
the button and the keyboard.
refs: #456

Fix for keyboard-bypass of field checks

---

examples/desktop/mapbook.xml

Add highlighting to search results

---

.travis.yml

- automatically sends change notifications to the #geomoose freenode IRC channel

add travis.ci notifications

---

docs/howto/configure-select-list.md
docs/howto/index.md

Added docs explaining how to configure select tool that selects from list of layers (or single layer) rather than all selectable layers.

Docs for select from list

---

examples/desktop/templates/parcel-columns.json
examples/desktop/templates/parcel-row.html
src/gm3/application.js
src/gm3/components/serviceManager.js
src/gm3/reducers/query.js

Now a feature can be removed from the results set from
a select. There was a state issue that required adding a
revision counter to the reducer.

Add the removal of a single feature to the demo

---

src/gm3/components/modal.js
src/gm3/components/serviceInputs/buffer.js
src/gm3/components/serviceInputs/length.js
src/less/modal.less
src/less/serviceForms.less

1. Fixes buffer running over to a second line by default.
2. Fixes issue with button layout in modal footers.

Styling fixes after skeleton migration

---

docs/howto/configure-search-or-fields.md

I added the field validation the the 'simple' search that allows you to search multiple fields in one box

Search simple validation

---

examples/desktop/app.js
examples/desktop/mapbook.xml
package-lock.json
src/gm3/actions/toolbar.js
src/gm3/components/toolbar/button.js

1. Adds the "single term for search" to the demo.
2. Adds a new `css-class` attribute to toolbar buttons
so built-in styles can be re-used.

Add Single-Search Field to Demo

---

docs/howto/add-a-plugin.md
examples/plugin/.babelrc
examples/plugin/package.json
examples/plugin/src/hello.js
src/gm3/application.js
webpack.config.js

This might _never_ get merged or expect the work to live on elsewhere.
This is an example of how one might build a react-based plugin for GeoMoose.

Add Plugin Support

---

docs/howto/change-buffer-units.md
docs/howto/index.md
examples/desktop/app.js
examples/desktop/templates/parcel-row.html
src/gm3/actions/map.js
src/gm3/application.js
src/gm3/components/map.js
src/gm3/components/serviceInputs/buffer.js
src/gm3/components/serviceInputs/length.js
src/gm3/components/serviceInputs/text.js
src/gm3/components/serviceManager.js
src/gm3/reducers/map.js
src/gm3/util.js
src/less/icons.less
src/services/select.js
tests/gm3/reducers/editor.test.js

1. Major clean up of selection feature state.
2. Adds a new small "buffer-select" services to the app
3. Adds the call to buffer-select to the desktop demo.
New buffer button to buffer feature
And does this

Add "Buffer from Select" feature

---

src/gm3/components/grid.js

Previous updates to the modal component broke
the open/close state management in the filter modals.
refs: #487

Fix for filter modals

---

package-lock.json
package.json

Basic npm audit fix update. Just some housekeeping.

Audit and update

---

src/gm3/components/layers/wfs.js
src/gm3/components/map.js
src/gm3/components/serviceManager.js
src/gm3/jsts.js

Using the shift-key lets the user select multiple features
from a set of results.
Buffers are also supported.

Add mulitple feature selection + buffer

---

src/gm3/components/map.js

After converting the selction over to allow for an array,
the wms-point identification was not working.
This changes the detection and selected feature.

Fix for identify bug

---

examples/desktop/mapbook.xml
src/gm3/components/map.js
src/gm3/components/serviceManager.js
src/gm3/lang/en.json
src/gm3/lang/es.json

This merge request is thanks to the pile of testing from @brentfraser 
1. Fix zoom to click when results are empty.
2. Add tooltip for clear results.
3. Handle AGS identify failures better.

3.6.1 Super Bug Fix Collection

---

AUTHORS

- add myself as a contributor to GM3 (providing MS4W builds, and docs)

add to AUTHORS

---

examples/desktop/mapbook.xml
src/gm3/actions/catalog.js
src/gm3/components/catalog/layer.js

Like it says on the tin. Uses the `tip` attribute.

Restore tooltips on layer titles.

---

src/gm3/components/map.js

Fixes a bug after the selction geometry definition changed.
refs: #520

Fix for identify on vector layers

---

src/gm3/components/layers/ags.js

Small fix to get more to the AGS layers.
refs: #517

Add custom params to AGS layers

---

src/gm3/application.js

- Adds `lonLatToMeters` to convert a lon, lat to web mercator.
- Adds `bboxToMeters` same song, but with a bounding box.
refs: #516

Add projection utilities to the Application class

---

docs/howto/hide-search-in-catalog.md
docs/howto/index.md
src/gm3/components/catalog/index.js

1. New `showSearch` prop that defaults to true.
2. Documented how to change it.

Add the option to hide search from the catalog

---

examples/desktop/mapbook.xml
src/gm3/actions/mapSource.js
src/gm3/components/editor/modal.js

Adds color, opacity, and size changes for stroke, fill,
and label styles.

Adding additional styling options

---

docs/howto/configure-search-or-fields.md

New doc to demonstrate how to do an ilike search
on a list of fields given a comma separated list
of input terms.

Add doc for doing a list of likes.

---

src/gm3/components/map.js

This should get applied before #558 and #559 then those will likely need to be rebased.

Fix lint/build errors.

---

examples/desktop/app.js
examples/desktop/index.html
examples/desktop/mapbook.xml
src/gm3/components/bookmark-modal.js
src/gm3/lang/en.json
src/gm3/lang/es.json
src/index.js
src/less/toolbar.less

We had a similar bookmark "Tab" in the old GeoMoose,
this creates a modal with a textfield that makes it
easy to copy the URL for bookmarks.

Add new Bookmark Modal

---

src/gm3/components/map.js

refs: #573 - Splitting up original MR to account for two different changes.

add boundedby property to WFS vectors

---

src/gm3/components/layers/vector.js
src/gm3/components/map.js

refs PR #573 
This is a clean up to break apart the commits.

allow passing user params in ags-vector map-source

---

docs/howto/ags-tile-example.md
docs/howto/index.md

Add AGS Tile usage documentation

---

examples/desktop/mapbook.xml
package-lock.json
package.json
src/gm3/components/layers/usng.js
src/gm3/components/map.js
webpack.config.js

Adds a new "usng" layer type for rendering USNG map collars

Add USNG Map Collar Support

---

package-lock.json
package.json
src/gm3/components/grid.js

NPM Audit Fixes

---

examples/desktop/mapbook.xml
src/gm3/actions/catalog.js
src/gm3/application.js
src/gm3/components/catalog/layer-checkbox.js
src/gm3/components/map/index.js
src/gm3/components/map/layers/blank.js
src/less/icons.less

- Adds the style to the catalog for radio buttons
- Honors the old multiple=false from GM2.x

Restoring radio-button groups

---

src/gm3/components/linearProgress.js
src/gm3/components/map/index.js
src/gm3/components/print/printImage.js
src/gm3/components/print/printModal.js
src/gm3/components/print/printPreviewImage.js
src/less/gm3.less
src/less/progress.less

1. Fixes the canvas selector based on the OpenLayers demo code
and tweaks from robinrullo.
2. Refactors and cleans up components for print.
3. Adds a progress bar which is handy for when big images
are coming in over the pipe.
refs: #640

Fix for high resolution print

---

src/gm3/lang/en.json
src/gm3/lang/es.json

Update en.json and es.json with some missing tool tips

---

src/gm3/components/favorites.js

`renderFlatTree` was missing a resolution parameter.
refs: #696

Fix for broken favorites list

---

src/gm3/components/grid.js

`undefined` was not a supported value by the mapbox filter
generator. This updates the query to force undefined to become
`''` (an empty string).
refs: #697

Fix issue with undefined values in the grid

---

package-lock.json
package.json
webpack.config.js

- Updates to new webpack version
- Cleans up old deps on the configuration for the dev server.

Switch to Webpack 5

---

docs/howto/configure-max-bufffer.rst
src/gm3/components/serviceManager.js
src/gm3/lang/en.json

- Adds docs for bufferMaxFeatures option.
- Updates modal to render the number of max features.

Add documentation for bufferMaxFeatures

---

src/gm3/components/print/printLayouts.js
src/gm3/components/print/printModal.js
src/gm3/lang/en.json

HT to @robinrullo for the fix.
refs: #673

Use pxToLayout units instead of just inches

---

src/gm3/actions/mapSource.js
src/gm3/components/grid.js
src/gm3/components/map/index.js

Safety checks were missing for pseudo-layers.
refs: #739

Fix for broken geocoder

---

examples/desktop/mapbook.xml
src/gm3/actions/toolbar.js
src/gm3/components/toolbar/button.js
src/gm3/components/toolbar/drawer.js
src/gm3/components/toolbar/index.js

Set `tip=` and go to town!
refs: #746

Allow setting tips on toolbar buttons and drawers

---

examples/desktop/mapbook.xml
src/gm3/actions/catalog.js
src/gm3/components/catalog/group.js
src/gm3/util.js

Allow metadata on groups

---

examples/desktop/mapbook.xml
src/gm3/actions/catalog.js
src/gm3/components/catalog/group.js

When present, a tooltip will be available for a group.

Add tips to groups

---

src/gm3/components/catalog/tools/upload.js

When no files are selected, skip to the end.

Handle zero files uploaded

---

src/gm3/components/catalog/tools/clear.js

Ensure that no means no, mister.
refs: #751

Fix clearing all features when clicking cancel

---

src/gm3/components/grid/filter-modal.js

- Fixes the logic for list filters.
- Adds a select all/none checkbox for list filters.
- Makes the behaviour of the clear button more predictable.

Fix for when setting multiple List filters

---

.github/workflows/tests.yml

Update tests to NodeJS 18.x and Ubuntu 22.04.

---

examples/desktop/app.js

Clears about both the query-string and the hash string.

Fix for "Start over" with query.

---

src/gm3/components/measure/calc.js
src/gm3/components/measure/index.js
src/less/serviceForms.less
tests/gm3/components/measure.test.js

Defaults the measure tool to a polygon.

Ensure measure has a default tool

---

docs/howto/change-loading-indicator.rst
src/gm3/components/serviceManager/index.js
src/gm3/components/serviceManager/loading.js

Includes docs 'n' things.
refs: #748

Make loading indicator configurable

---

src/services/findme.js

- EnableHighAccuracy
- Alert on Error

FindMe fixes

---

package-lock.json

NPM Audit for 2024 November

---

examples/desktop/mapbook.xml

fixes https://github.com/geomoose/gm3/issues/869

Fix for Out of Date Demo Rest Services

---

examples/desktop/mapbook.xml

Last of the Dakota county service updates for https://github.com/geomoose/gm3/issues/869

More out of date demo rest services

---

src/gm3/reducers/mapSource.js
src/services/findme.js

This makes it easier to reference, remove, edit, change the results of the find me service.
refs: #333

Place find me results on the sketch layer

---

examples/mobile/package.json

Audit fixes and remove un used deps.

Update mobile package.json
