- .gitignore
- demo/config.js.example
- demo/index.html
- demo/test.html
- demo/test.js
The mighty return of `config.js`, now makes it
easier to adapt to different environments without changing the
code.
1. Moves the mapserver and mapfile root  out of test.js.
2. Adds an ignore for config.js to prevent it from being added to the repo.
3. Changed BING_KEY to use CONFIG.bing_key.
> Moved mapserver variables to config.js

- Gruntfile.js
Two changes:
1. Add a `watch` subtask for Less modifications
1. Currently, the `serve` task calls the two `watch` subtasks, `watch:gm3` and `watch:services`. Grunt begins running `watch:gm3`, but the watch tasks never finishes, and therefore `watch:services` never runs. 
This problem is solved by running the `watch` group as a whole. This will allow all three watch subtasks: `watch:gm3`, `watch:services`, and `watch:less` to be run concurrently upon running `serve`
> Adjust gruntfile for Less modifications

- CONTRIBUTORS.md
- demo/test.css
- src/gm3/components/toolbar.jsx
- src/less/gm3.less
- src/less/toolbar.less
Additional styling suggestions welcome.
* The new style is constrained slightly by the fixed height of the header (75px, and therefore toolbar: 25px). 
* The buttons have hover affordances (underlines, pointer-cursors) to indicate their selectability.
* Individual icons are specified via CSS 
* Having to specify individual icons in the CSS is messy:
```less
.tool-measure {
.icon {
.fa; // extend font-awesome to include generic icon styles
&:before {
content: @fa-var-arrows-h; // specify particular icon to be used 
}
}
}
}
```
> Updated Toolbar Styling 

- package.json
`./tests/` wasn't a valid path on windows.  Dropping the relative paths fixes that.
> Fixed path issue with tests on windows.

- src/services/geocode-osm.js
Effectively the same as the Bing Geocoder, updated for the OSM API.
> OSM Geocoder

- src/gm3/components/version.jsx
Although it didn't affect anything, the "version" component class was named "Toolbar".
> Change name of version component to Version

- src/gm3/components/layers/wms.js
Forgot to set the default FORMAT parameter. That was causing the legend to
not generate.  Defaults to PNG, this can be overriden in the map source
definition.
> Fix for broken WMS legend graphics.

- src/gm3/components/map.jsx
- src/gm3/components/serviceManager.jsx
- src/less/gm3.less
When drawing or selecting, the user can now "stop" or "end" the
drawing/selection process.  They can start it up again by clicking
the appropriate radio button from the service or a tool from a layer.
> Added "stop" control for drawings.

- src/gm3/application.jsx
- src/gm3/util.js
- src/services/geocode-bing.js
- src/services/geocode-osm.js
This removes the need to have an application scope to use an XHR call.
As it's a generally useful utility, I think putting it in util is more
logical anyway.
> Moved "xhr" function to util.

- examples/desktop/mapbook.xml
- package.json
- src/gm3/actions/mapSource.js
- src/gm3/application.jsx
- src/gm3/components/grid.jsx
- src/gm3/components/layers/vector.js
- src/gm3/components/map.jsx
- src/gm3/reducers/query.js
- src/gm3/util.js
- src/services/select.js
- tests/gm3/util.test.js
This PR accomplishes a few things:
1. Removes the custom filtering that I wrote to handle the grid filtering in favor of using the more feature complete mapbox "createFunction".  All the necessary components have been updated to reflect that.
2. Adds a new "transform" tag to layers so that a data type can be specified for a particular attribute.  When we get to feature editing this will probably need to come up again as we'll actually want more metadata about columns than this functionality provides.
3. The "highlight" layer has been removed in favor of an internal "results" source and layer.  That "results" layer is the one that is tied to the same display as the grid.  Ergo, both the grid and the layer will match when a filter is set for a query.
4. Multiple "layers" can now be defined …
> Create a "smart" layer for rendering query results.

- src/gm3/components/serviceManager.jsx
The measure tool was being handled as a special case,
this avoids that to a better degree.
Fix for issue #87
> Fixed measure-tool state special case.

- examples/desktop/app.js
- src/gm3/application.jsx
- src/gm3/components/coordinates.jsx
- src/gm3/util.js
This is still a bit of a work in progress. Questions/comments:
1. I didn't add a coordinate transform property (yet) in favor of proj/wkt strings
```Javascript
{
label: 'UTM15',
ref: 'EPSG:26915',
// pretty
projDef: '+proj=utm +zone=15 +ellps=GRS80 +datum=NAD83 +units=m +no_defs'
}
```
> We may need to add a function to application or util to "bridge the gap" to allow users to add a projection.
2. @theduckylittle would it make sense to keep projection definitions out of the coordinate display options? And then simply reference the defined projection in the coordinate display option:
```Javascript
// app.js
// define projection
app.addProjection({
ref: 'EPSG:26915',
def: '+proj=utm +zone=15 +ellps=GRS80 +datum=NAD83 +units=m +no_defs'
});
// then refer to it …
```
> Specify coordinate projection

- examples/desktop/app.js
- src/gm3/components/toolbar.jsx
Added a new UI hint that indicates when a service is "started."
This brings the super tab "to the top" whenever a user clicks to
start a service.
> Always hint to open the super tab. refs: #81

- src/gm3/components/coordinates.jsx
Coordinate display wasn't fully upgraded to ol4/es6 classes during the merge.  This fixes that.
> Fix for non-es6 ol inclusion.

- src/gm3/components/map.jsx
Ensures the extent is properly processed.
Fix for #97
> Stop drawing when changing services.

- .travis.yml
It looks like travis-ci updated their default node from v7.10.0 to v8.0.0.  This means the iltorb module is not available as a binary and needs to be built from source.  This in turn requires a C++11 compiler which in turn requires update the distro from Ubuntu Precise to Trusty.
> Attempt to fix travis-ci builds

- src/gm3/components/serviceManager.jsx
1. ENTER in an input is the same as clicking "Go".
2. ESCAPE in an input is the same as clicking "Close".
3. The first input element will be selected after render.
Refs: #61 , #94
> Added keyboard short-cuts.

- examples/desktop/mapbook.xml
- src/gm3/application.jsx
1. Removed the missing template from the mapbook
2. Reworked the getTemplate promise to ALWAYS resolve, it now resolves to a blank template on failure to load.
> Fixed the failing template issues.

- examples/desktop/app.css
- examples/desktop/debug.html
- examples/desktop/index.html
- examples/desktop/tabs.css
Scrolling tabs was causing the tab headers to scroll off.
> Fix for tab overflow scrolling bug.

- src/gm3/components/serviceInputs/text.jsx
- src/gm3/components/serviceManager.jsx
Old bug: select, change to rail roads, go = rail roads.
select, shows parcels selected, go = rail roads (should be parcels).
This was because the local "state" in the service manager has the value
set to rail roads yet parcels are what needed to be set.  This ensures the
inputs show what the service manager thinks they should be.
Follow up work: put more service info into the state tree.
> Fix for "forgetting" select setting.

- examples/desktop/mapbook.xml
Switch to using https for remote source in the mapbook where
available.  This is necessary when GeoMoose is hosted via https 
(like the demo) to avoid browser warnings.  This still works fine if 
GeoMoose is hosted via http.
> Use https for remote sources in mapbook.

- src/gm3/application.jsx
- src/gm3/components/catalog.jsx
1. Small change in catalog to remove a console.log that got
merged in accidentally.
2. Added "selectable: true" the results/highlight layer which
allows users to do things like "Search for a parcel", select that
parcel from the map, then buffer that shape to get other features.
> Allow selecting features from the results layer.

- src/gm3/actions/mapSource.js
IE treats the returns form getElementsByTagName as a "collection" instead of as a basic array and therefore support for ES6 "of" operator doesn't transpile correctly.  This fixes the transgression.
> Fix for IE iterator bug.

- examples/desktop/mapbook.xml
1. fixed the scale bar layer names.
2. removed a pile of cruft.
3. The metadata links for parcels now points to the
LICENSE on github for parcels.
> Cleanup of mapbook pre-release.

- src/gm3/application.jsx
- src/gm3/components/grid.jsx
- src/gm3/components/toolbar.jsx
- src/less/results.less
- src/less/toolbar.less
- src/services/findme.js
- src/services/geocode-bing.js
- src/services/geocode-osm.js
- src/services/identify.js
- src/services/search.js
- src/services/select.js
- src/services/zoomto.js
Adds the ability to min/maximize the grid. The button even
does a fancy icon change.
Other included changes:
1. This also cleans up some of the differing CSS between the toolbar
and the grid.  Longer term, we should initiate a project that
reuses more components but for now, it seemed like a good idea
to at least fix the CSS better.
2. Fix for the missing highlight functions (merge or stupidity caused them to get chucked, I'd imagine).
3. Fix for module.exports being undefined.  The polyfill now is smarter and does a typeof check on module to ensure that the module 'api' exists before trying to use that object.
refs: #124
> Toggle Grid Display

- examples/desktop/app.js
- examples/desktop/mapbook.xml
- src/gm3/actions/mapSource.js
- src/gm3/application.jsx
- src/gm3/components/catalog/tools.jsx
- src/gm3/components/catalog/tools/upload.jsx
- src/gm3/components/layers/vector.js
- src/gm3/components/map.jsx
- src/gm3/reducers/mapSource.js
- src/gm3/util.js
- tests/gm3/components/map.test.jsx
- tests/gm3/reducers/mapSource.test.js
1. typename is no longer inferred for WFS layers,
it's a required parameter.
2. ags-vector layers must now specify the *full* path
instead of inferring it from the layer name.
3. `layer`s in vector layers are now basically for styling.
They work with the list of features that have been returned
from the vector source.  The mapbook hsa been updated to show
"expensive" parcels as an example.
4. Properties are now transformed when injested from vector sources
as well as from queries.  This allows the user to force the datatype
of a feature property.
5. The mapbook and app.js has also been updated in the desktop example
to use "common names" instead of direct layer names to prevent
confusion and conflation.
> Major update to vector layer handling.

- examples/desktop/mapbook.xml
- src/gm3/actions/mapSource.js
- src/gm3/components/layers/ags.js
- src/gm3/components/layers/xyz.js
- src/gm3/components/map.jsx
- src/gm3/components/print/printImage.jsx
- src/gm3/reducers/mapSource.js
1. Added a `printable` attributes to map-sources.
This defaults to true but is set to false for the WMF Labs tiles
which do not support cross origin printing. Note: this may work
with some apache header settings but I haven't tested it yet
and not wanting to enforce web-server rules I made the decision to
make this just not-printable.
2. Commented out Bing layers.
These don't work without a key from Bing. When the tutorials
are published they will include how to add back in Bing layers.
3. Made specifying the cross-origin parameter more clear.
OpenLayers will set a CORS header when given a little information,
the ol.source.OSM class sets this to anonymous by default but I
didn't want to map any additional layer type when XYZ layers will
work fine with the additional parameter.  This can …
> Major bug fixes for printing

- Gruntfile.js
- webpack.config.js
Removed "watch" from the grunt serve script. This has the downside
of not automatically rebuilding the Less files but it makes the
development of Javascript SUBSTANTIALLY faster as it will do
individual module replacement instead of a full dev-build.
> Speed ups for Dev development.

- Gruntfile.js
- src/gm3/components/print/printImage.jsx
- src/gm3/components/print/printPreviewImage.jsx
- webpack.config.js
Misconfigured raster sources can cause the canvas to throw
an error.  The dialog is now improved to detect that and tell the
user that there may be a misconfiguration.
addresses #151 
side-effects: depends on PR #163
> Better handling of "tainted" canvases.

- .npmignore
The source URLs in geomoose.min.js.map are all webpack relative
which can't resolve to anything in production.  This reduces the
output pack size from 8.5MB to 5.9MB.
Note: This doesn't change the embedded source map in geomoose.js.
> Don't package useless source map.

- src/gm3/util.js
Regression repair! When the features were moved to the mapsource
instead of the layer, the extents function was not updated.
This fixes it.
> Fixed broken zoom-to layer extents tool.

- examples/desktop/app.css
- examples/desktop/mapbook.xml
- src/less/results.less
1. Cleaned up the template for pipelines.
2. Added an example of how to tailor the CSS + the
template to do something specific for a given layer (pipelines)
3. Cleaned up the LESS/CSS to make the identify results a bit shorter
and a bit better looking.
> Attempt to make identify look less ugly.

- src/gm3/reducers/query.js
The "keep only one" setting was not deleting the old
queries in the background.  That was causing the memory
usage to explode over repeated queries.
> Fix for zombie queries.

- src/gm3/components/map.jsx
Without FEATURE_COUNT set only one feature per layer would be returned.
This now lets up to 1000 features be returned.
refs: #176
> Fix for single-identify returns.

- src/gm3/actions/mapSource.js
- src/gm3/application.jsx
- src/gm3/components/map.jsx
- src/services/identify.js
1. There are situations in which MapServer returns a 200 status code
but the "response" is not valid. This was causing a dead end for
identifying layers that has now been fixed.
2. Added a "filter" to the getQueryableLayers function which will
allow services to defined a required template before querying them.
e.g. `getQueryableLayers({withTemplate: 'identify'})`.
> Fixed two identify bugs.

- src/gm3/actions/catalog.js
`show-legend` will ensure a legend is not displayed for a layer.
This was in 2.x and is now in 3.0.0.
> Fixed missing show-legend support.

- examples/desktop/app.css
- examples/desktop/app.js
- src/gm3/actions/mapSource.js
- src/gm3/application.jsx
- src/gm3/components/map.jsx
- src/gm3/components/serviceInputs/layersList.jsx
- src/gm3/components/serviceInputs/select.jsx
- src/gm3/components/serviceManager.jsx
- src/less/serviceForms.less
- src/services/select.js
1. Added new `layers-list` type select that can be used
to generate a list of layers based on template filters.
2. Cleaned up and enhanced some of the default desktop app CSS.
> CSS Tweaks and new LayersList Control

- src/gm3/components/layers/vector.js
- src/gm3/components/map.jsx
1. Added the ability to load a map using the GeoJSON return.
2. Updated queries to switch between XML and JSON.
To have WFS queries return GeoJSON set the outputFormat parameter
to 'application/json'.  E.G.:
```xml
<map-source ...>
<param name="outputFormat" value="application/json" />
</map-source>
```
> Added support for WFS + GeoJSON

- src/gm3/actions/catalog.js
- src/gm3/components/map.jsx
- src/less/icons.less
1. New code actually forces refreshes more reliably
(moving from date/getms to uuid)
2. Fixed the icon to use FA instead of MapSkin
3. Fixed parser to ensure that refreshEnabled is set to default.
> Fixed refresh layer issues:

- .travis.yml
- src/gm3/application.jsx
1. Fixed travis to include the `canvas` module for testing.
OpenLayers is using document.createElement('CANVAS') to create
a dummy tile in the background. This causes issues within the
test framework as jsdom does not implement the Canvas API fully
without using the npm canvas module.
That module is onerous to install on Windows so I have not made
it a requirement in the package.json as this time.
2. Removed an unused inclusion of the Map component from Application
which was causing that package to fail though it was not causing
errors.
> Fixing tests

- docs/howto/add-select.md
Not having this in a map-source that you want to be select-able will cause the WFS to throw an error.
> Add reminder that WFS requires typename in map-source

- docs/howto/add-select.md
A code block was not properly closed causing the file
to appear truncated.
refs: #210
> Closed code block in add-select

- src/gm3/components/catalog/tools/upload.jsx
- src/gm3/components/serviceManager.jsx
- src/less/gm3.less
1. Normalized the CSS for a progress spinner into the 'spinner'
class name.
2. Spinner is now used by the service manager tab for loading.
3. Upload dialog now tracks its own progress. It will also show
the number of features uploaded to the layer when finished.
4. Errors are no longer silent. But it is a pretty standard
"something went wrong" error message.
> Upload dialog enhancements

- src/gm3/application.jsx
- tests/gm3/application.test.js
Previous version was passing in {lon, lat} when it should've
been [lon, lat]. This is likely a cruft that was never tested.
refs: #214
> Fix for broken zoom-to issue.

- src/gm3/components/serviceManager.jsx
Previously, the summary would show for any service whether
or not it actually was querying layers + features. This was problematic
and is solved by allowing a service to set this.showHeader = false.
Refs: #220
> Added showHeader toggle to hide service summary

- docs/index.md
- docs/quickstart-ec2.md
- docs/quickstart.md
1. Added workshop link to the docs index.
2. Added quickstart for EC2
3. Added NVM notice to the dev quickstart.
@elil  - Hope this is a bit better than what we have before
@klassenjs - I've worked through the EC2 instructions.  I didn't want to write an entire EC2 primer but I'm sure there's room for a lot of improvement.
> Documentation updatesfor quickstarts.

- package.json
Note: there is still:
```
npm WARN deprecated babel-preset-es2015@6.14.0:   Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
```
Following the recommendation of replacing `babel-preset-es2015` with `babel-preset-env` breaks the build with multiple instances of:
```
Module build failed: ReferenceError: [BABEL] ./gm3/src/index.js: Unknown option: foreign.__esModule. Check out http://babeljs.io/docs/usage/options/ for more info
```
I don't know where __esModule is coming from.  preset-env is supposed to be equivalent to es2015,es2016,es2017,es-latest.
> Fix babel deprecation warning

- src/gm3/components/map.jsx
When the user removes all the query results the map will now
remove all the features from the results layer.
refs: #230
> Fix for map not auto-clearing.

- src/gm3/components/serviceInputs/select.jsx
- src/services/select.js
When defaultValue is undefined for a select, it was setting the
first value as the default but was during the render() cycle
which was causing an infinite loop.
refs: #237
> fix for setting the default value when undefined

- examples/desktop/app.js
- examples/desktop/mapbook.xml
- examples/desktop/templates/parcels.html
- src/gm3/actions/mapSource.js
'query-as' is a list of paths (colon delimited) which are used
for querying in the place of a specific layer.  This allows a
raster map-source (e.g. WMS) to transparently switch to vector
sources (e.g. WFS) when performing a select or search operation.
refs: #240
> Created new 'query-as' attribute for layers.

- src/gm3/actions/map.js
- src/gm3/application.jsx
- src/gm3/components/map.jsx
- tests/gm3/application.test.js
This fixes an expectation bug more than anything else.
After meeting with some users, and looking at the other
Javascript/GIS APIs, conceptualizing a "zoom" level is easier
than necessarily specifying a resolution.
refs: #242
> zoomTo now zooms to a zoom level and not a resolution.

- src/gm3/components/catalog/tools/upload.jsx
*.geojson, *.json, *.kml
Tested: FF52 Linux. IE 11 and Chrome 61 Windows
Refs: #29
> Limit file upload dialog to supported types.

- src/gm3/components/catalog/tools/upload.jsx
Windows was not checking the mime-type properly. File.type was
consistently set to ''. This uses the (inferior) filename test
in order to detect the type of parsers which should be used.
refs: #235
> Updated KML filename sniffer for windows compat

- docs/howto/add-search-layer-picker.md
- examples/desktop/app.css
- examples/desktop/app.js
- examples/desktop/mapbook.xml
- src/gm3/application.jsx
- src/services/search.js
1. Search no longer pre-defines parcels.
This change was made to add clarity to show what search was
already doing internally.
2. Added the ability to override the searchLayers with a function.
getSearchLayers is passed this.searchLayers and fields.  This will
allow users to change which layres are searched based on inputs.
3. Updates to show off the new multi-field search capability in the desktop
demo.
> Improvements to search

- examples/desktop/mapbook.xml
- src/gm3/components/grid.jsx
1. Previous version of list assumed the pick list was
a set of unique values which wasn't strictly true.
2. Created a demo by using city names with the parcel grid.
refs: #255
> Added uniqueness check for grid's list filter

- .travis.yml
- src/gm3/components/serviceManager.jsx
- src/less/serviceForms.less
After all queries have been removed from the selection tab,
the selection polygon would continue to be displayed.
This new functionality fixes that issue by adding a button
allowing the user to clear the polygon.  This was done as a bit
of a compromise. Ostensibly, a complex selection area may need to be
re-used even if the user wants to clear teh current results.  Automatically
removing the selection area would've made that impossible.
Steps to use:
1. run a query with a drawn selection feature.
2. click "delete" / trash-can icon on the results.
3. See that there is now a polygon on display.
4. click the 'clear' button in the service manager tab.
refs: #257
> Added a control to allow clearing selections

- examples/desktop/mapbook.xml
- src/gm3/application.jsx
- src/services/geocode-osm.js
1. Renamed the address geocoder to increase clarity.
2. Fixed the issue with fixed templates not rendering.
3. Switched the templates to zoomTo instead of zoomToExtent,
making the view a bit more reasonable.
refs: #277
> Rename and Repairs for OSM Geocode

- src/gm3/components/map.jsx
- src/services/search.js
The settings of using "*" and "\_" didn't appear to work
with SQL sources.  This version uses the "%" and "_" conventions
that are more similar to SQL.
refs: #279
> Tweak WFS settings to use "%"

- .travis.yml
- package.json
Looks like implicit `npm install` is no bueno.
> Attempt to fix travis build errors.

- examples/desktop/debug.html
- examples/desktop/index.html
site.css is referenced in the docs as a suggested place for a site
admin to place their site-specific CSS rules.  However, as it is
not a shipped file, it is causing 404 errors in the desktop
example that while harmless are nonetheless concerning for users.
ref: #276
> Comment out site.css.

- src/tasks/grunt-less-linter.js
Looks for \t's throws errors when they are there.
refs: #290
> Added a tab check to the less linter.

- docs/_includes/footer.html
Looks like icon-github.html was replaced with social.html in the
minima theme.
> Fix GitHub pages build failure.

- src/gm3/components/map.jsx
Controls for the map will now be manually specified and limited
to the zoom and rotate controls.
> Manually specify default map controls

- src/gm3/components/coordinate-display.js
- tests/gm3/components/coordinates.test.js
- Centralizes format output logic.
- Fixes issue with precision test.
refs: #318
> Fix for precision handling

- src/gm3/components/coordinate-display.js
Looks like this was lost in 6ef3b42c.
ref: #337
> Restore X,Y label to coordinate-display.

- README.md
- package-lock.json
- package.json
- src/gm3/application.js
- src/gm3/components/catalog/tools/download.js
- src/gm3/components/catalog/tools/upload.js
- src/gm3/components/coordinate-display.js
- src/gm3/components/layers/ags.js
- src/gm3/components/layers/bing.js
- src/gm3/components/layers/vector.js
- src/gm3/components/layers/wms.js
- src/gm3/components/layers/xyz.js
- src/gm3/components/map.js
- src/gm3/components/measure.js
- src/gm3/components/print/printModal.js
- src/gm3/util.js
- src/index.js
- tests/app.test.js
- tests/gm3/components/map.test.js
- tests/setup.js
1. Upgrade to OpenLayers 5.
2. Map tests are skipped when `node-canvas` is not present.
> OpenLayers 5 Upgrade, Tests no longer require canvas

- examples/desktop/app.js
- package.json
- src/gm3/components/serviceForm.js
- src/less/serviceForms.less
- src/services/search.js
This pull request allows the user to add validation to the search fields. It is achieve using the new `validateFieldValues` method of the search service. This method takes as an argument the field values (object `{fieldName: value}`) and returns a boolean value that indicate if the input is valid and a correspondent error message (object `{valid: boolean, message: string}`).
The main changes are in `serviceForm.js`:
- two new state property were added `validateFieldValuesResultMessage` and `lastService`,
- a div message for the error was added, that shows in case `validateFieldValuesResultMessage` is not null
- an invocation to the service `validateFieldValues` is made, if exist, on the click event of the go button
- the component `UNSAFE_componentWillUpdate` method was added to udate the …
> search field values validation

- examples/desktop/mapbook.xml
- package.json
- src/gm3/actions/catalog.js
- src/gm3/actions/mapSource.js
- src/gm3/components/catalog/layer.js
- src/gm3/components/layers/ags.js
- src/gm3/components/layers/bing.js
- src/gm3/components/layers/vector.js
- src/gm3/components/layers/wms.js
- src/gm3/components/layers/xyz.js
- src/less/catalog.less
1. Added suppot for `minresolution` and `maxresolution`
to map-sources and catalogs.
2. Added default CSS to style the layers.
3. Added example to mapbook.
> Adding Min/Max-resolution support to catalog + map

- src/gm3/components/serviceInputs/layersList.js
The layerslist input filter was dropped at some point,
this fixes that oversight.
refs: #357
> Restore layerslist input filter

- examples/desktop/app.js
- examples/desktop/mapbook.xml
- src/gm3/actionTypes.js
- src/gm3/actions/config.js
- src/gm3/application.js
- src/gm3/components/map.js
- src/gm3/jsts.js
- src/gm3/reducers/config.js
- tests/gm3/jsts.test.js
1. Fixed the buffer calculation by doing the manual
conversions in/out of traverse mercator.
2. Added the ability to enable openlayers scaleline
indicator which was also correctly 'measuring' the
distance represented on the map.
2b. I added a config reducer as a catch-all of app settings that
may not necessarily be best interpreted by the mapbook.
This may be fluid and should likely allow the user to change
settings if a developer gets ambitious.
3. Dropped the misleading mapserver scalelines from the
desktop demo mapbook.
> Fixing buffer and scale distances

- src/gm3/components/map.js
- src/gm3/components/serviceForm.js
- src/gm3/util.js
ServiceForm expected to be re-created when switching
services, this creates a better test and resets the values
to ensure they don't carry from incomplete service to incomplete service.
> Fix state bug with switching services

- selenium/tests/basic.py
Was hard coded to 17, but sometimes the mapbook changes.  Allow to
pass when > 10, so this isn't so fragile.  The main goal is to see
if IE11 works at all.  More detailed tests can follow if needed.
ref: #391
> Fix selenium layer count check.

- examples/desktop/app.js
- src/gm3/components/serviceManager.js
1. Adds default setting for the select-able layer.
2. ServiceManager will now ensure the default values are
used before passing the fields list to a service.
Bonus! Cleaned up the dead code of ServiceManager.startQuery.
> Fix for Selecet + autoGo=true

- src/gm3/components/map.js
- src/gm3/components/serviceForm.js
- src/services/select.js
Adds the box drawing tool to the set of options
for Select.
refs: https://github.com/geomoose/gm3/issues/408
> Add Box drawing

- src/gm3/components/serviceManager.js
Require inputs to be filled out (including buffer)
before submitting a form.
A console.error will appear when this is misconfigured.
refs: https://github.com/geomoose/gm3/issues/407
> Prevent autoGo triggering invalid state

- src/gm3/components/layers/wms.js
`cross-origin` properties were not being honoured
on WMS layers.
refs: https://github.com/geomoose/gm3/issues/406
> Fix for cross-origin WMS requests

- examples/mobile/index.html
- examples/mobile/mobile.css
- examples/mobile/mobile.js
- examples/mobile/package.json
- src/gm3/components/catalog/group.js
- src/gm3/components/map.js
- src/gm3/reducers/config.js
- src/less/catalog.less
- tests/gm3/components/catalog.test.js
1. Remove jquery mobile and switch to bootstrap
for the useful css resets.
2. Fix a CSS namespace clash with collapse and expand.
3. Fix a bug found with the config. The map would go wonky
if a configuration was not provided.
4. Cleaned up the logic for default map config settings.
refs: #399 #400 #401
> Fixes for mobile branch

- examples/desktop/mapbook.xml
This should enable the demo print option to work with the demo WMS now that the cross-origin param is respected (https://github.com/geomoose/gm3/issues/406)
> Add cross-origin parameter to WMS layer in demo

- examples/desktop/app.js
- examples/desktop/mapbook.xml
- src/gm3/components/print/printModal.js
- src/gm3/components/scaleline.js
- src/gm3/components/serviceForm.js
Draws a scaleline on the PDF when configured
to do so. The settings are the same ones used
to render the scaleline for the map.
refs: #398
> Add a scaleline to the print out

- src/gm3/components/measure.js
`<CoordinateDisplay>`, used to display the results of measure point,
needs the resolution parameter to know how many digits to display
for USNG coordinates.  Otherwise, it defaults to displaying no
digits (100km resolution).
> Measure point: Display correct USNG resolution

- src/gm3/components/serviceManager.js
When "End Drawing" is clicked it sets the interactionType to null.
However, when re-clicking the same service, this was causing a weird
null-state to be displayed to the user. They had started the service
but no drawing tool would be selected.
This restores the drawing tool to the default no matter what.
> Fix issue with disappearing tool interaction

- README.md
BrowserStack moved API fucntions from `www` to `api`.
> Update BrowserStack URL

- docs/howto/configure-measure-tool.md
- examples/desktop/app.js
> Update the measure tool how to to include initialUnits

- src/gm3/components/serviceForm.js
This is a future port to allow hidden values in
the service definition.
> Add 'hidden' Input Type

- examples/mobile/mobile.js
- src/gm3/application.js
Previous fix for starting a service's default tool broke
the implementation for mobile. This fixes it.
refs: #399
> Fix identify button on mobile

- src/services/search.js
I added header and footer templates to the search service in the same way as the select service. To take advantage of this you would have to add 'search-header' templates to the map-source in the `mapbook.xml` just as you would for the select service. Feel free to incorporate this, modify it, or throw it out.
> Added header and footer templates to search results

- src/gm3/application.js
- src/services/select.js
1. Add a sanity check to `startService` to prevent an error when
a caller fails to pass in options.
2. Add the `changeTool` option to the `startService` call in
Select when there is an empty geometry.
refs: #470
> Fix for empty geometry losing tools

- package-lock.json
- package.json
- webpack.config.js
Adds the standard whatwg-fetch polyfill to fix the error
on IE11 with calling fetch.
refs: #472
> Fix for missing IE11 Fetch Polyfill

- docs/howto/configure-search-or-fields.md
- docs/howto/index.md
Describes how to change the search service configuration to
support "or" searches by both:
1. Allowing specific fields to be joined by "OR"
2. Hide the specific search fields from the user.
By using a single unified search term.
> Add documentation for "or" type searches

- examples/desktop/tabs.css
Style updates meant the tab-togglers "arrow" was transparent
and was causing but click-ability issues and visibility issues.
This MR adds the background that fixes that.
Supersedes #447
> Fix for tab-toggler background color

- package-lock.json
- package.json
- src/gm3/actions/mapSource.js
- src/gm3/application.js
- src/gm3/components/layers/vector.js
- src/gm3/components/map.js
- src/gm3/util.js
Previous Mapbox GL to OL style library was deprecated.
This new version is more full featured. Updated the
vector layer class to also check the spec for divving up
the properties between paint and layout sections.
> Update to ol-mapbox-style

- src/gm3/components/drawTool.js
If the Select tool is the default (pick-a-feature-from-alayer)
then it was not setting the appropriate default interactive layer.
This checks to ensure that when Select is the default it will
use the first layer that is active.
refs: #438
> Fix default state of activeSource for select

- examples/desktop/app.js
- src/gm3/components/map.js
- src/gm3/components/serviceManager.js
- src/services/select.js
1. `keepAlive` will keep the users last draw tool active for the service.
When the user draws a new feature then it will go back to the service-form.
This is in contrast to `autoGo` which assumes no input from the user.
2. The `keepAlive` property is now set to true in the demo app.
This show cases how the user can repeatedly draw a new polygon.
And keep changing settings.
> Fix broken keepAlive setting and add it to Select.

- examples/desktop/app.js
- src/gm3/components/layers/wfs.js
This builds on the single-search terms search.
It can search multiple fields and the order of terms won't matter.
For example "terry little" and "little terry" will now return the
same list.
> Support a list-of-ilikes search

- examples/desktop/app.js
- src/gm3/actions/map.js
- src/gm3/application.js
- src/gm3/components/grid.js
- src/gm3/components/map.js
- src/gm3/components/serviceManager.js
- src/gm3/util.js
- src/services/search.js
- src/services/select.js
- tests/gm3/util.test.js
1. Allow a service to zoom to its results after it's finished.
2. Allow the grid to stay minimized when the service finishes (instead of always being "maximized").
> Additional Service Options

- src/gm3/components/catalog/legend.js
- src/gm3/components/layers/wms.js
- src/gm3/util.js
- tests/gm3/components/layers/wms.test.js
1. Adds new scale calculation function (heavily lifted from the OL code base).
2. Adds `SCALE` parameter to WMS GetLegendGraphic requests.
> Add scale-based smarts to WMS legends

- src/gm3/components/map.js
The dictionary was incomplete. This simplifys the logic.
refs: #495
> Fix translation of drawing tools.

- src/gm3/application.js
- src/gm3/components/map.js
1. Padding in an undefined or null zoom was causing issues on
restore.
2. Also fixed the bug with directly calling `startService`:
a. The tool was not being activated.
b. The UI hint was not being triggered to show the super tab.
> Fix for service startup and hash tracking issue

- src/gm3/components/grid.js
If the previous query was cleared with no replacement
the grid would throw an error since the query was undefined.
refs: #501
> Added sanity check to grid to prevent error on undefined query

- examples/desktop/mapbook.xml
1. The B&W OSM layer no longer supports CORS. This removes it so
that it appears less buggy.
2. Retitle the OSM layer to just say OSM.
> Drop Black and White OSM layer.

- src/gm3/actionTypes.js
- src/gm3/actions/service.js
- src/gm3/components/map.js
- src/gm3/components/serviceManager.js
- src/gm3/components/toolbar/button.js
- src/gm3/components/toolbar/drawer.js
- src/gm3/components/toolbar/index.js
- src/gm3/lang/en.json
- src/gm3/lang/es.json
- src/gm3/reducers/query.js
- tests/gm3/components/toolbar.test.js
1. When a tool is "Restarted" it returns the form and
settings from before.
2. When switching tools the defualt tool is always selected.
3. The "stop tool" on the map now uses the service name as available.
> Improvement to service-life-cycle and tools

- docs/index.md
The "###" don't create depth but use increasingly specific headers. For the final "links" those will format more cleanly as al list.
> use a bullet point style instead of a header

- src/gm3/components/serviceInputs/select.js
There was an issue with the Selects not properly updating
their value when the default was missing.
refs: #514
> Fix for Select input when the default is missing

- examples/mobile/mobile.js
- src/gm3/components/serviceManager.js
1. Added new hint to indicate new results.
2. Fixed mobile to use that new hint.
refs: #519
> Fix for service return not going to results tab

- examples/desktop/app.js
- examples/desktop/mapbook.xml
- src/gm3/components/layers/vector.js
- src/gm3/components/map.js
The change in vector.js allows the user supplied params in a WFS map-source to over-ride the default GM params (unfortunately the param names are case-sensitive).
> fixes for WFS and AGS server requests

- examples/desktop/app.js
- src/gm3/actionTypes.js
- src/gm3/actions/ui.js
- src/gm3/application.js
- src/gm3/components/map.js
- src/gm3/components/print/printLayouts.js
- src/gm3/components/print/printModal.js
- src/gm3/lang/en.json
- src/gm3/lang/es.json
- src/gm3/reducers/ui.js
1. New print layout which demos legends.
2. Fixes issue with needing to expose `setState` of modals
which is a react anit-pattern (new store-drive `showModal` function
is available through Applicaiton).
3. Works out all the async business with loading the images
and then rendering the PDF.
refs: #327
> Add Legend Printing

- src/gm3/components/bookmark-modal.js
URL's can be long and larger than box they are in. A hyperlink allows users to right click and copy rather than manually copying the entire link.
Credits to @chughes-lincoln , this is just a clean up of the git history.
> Included clickable link

- src/index.js
The DuckDuckGo Privacy Essentials extension for Firefox and Chrome
injects anonymous script elements into the webpage.  This breaks
an assumption in index.js that all script elements have a valid
src attribute.
In the name of defensive coding and playing well with others,
this commit protects access to the src element with a null check.
However, this seems like very sketchy behavior to me on the part of
DDG PE.  It appears identical to a malicious code injection attack.
And I'm really not sure how we are supposed to reliably code for an
environment where the definition of the environment, and even our
own application code, can be changed out from under us at any time.
fixes #607
> Work around for DuckDuckGo Privacy Essentials

- src/gm3/components/map.js
One line, one word, one fix!
The view configuration was missing the `extent` keyword to mix-in
to the object.
refs: #609
> Fix missing extent limitation bug

- src/gm3/components/coordinate-display.js
- src/gm3/components/coordinates.js
As the zoom level changes, the user will be presented with
different levels of precision on the latitude and longitude.
refs: #304
> Add Automatic Precision to Lat/Lon Display

- src/gm3/components/serviceInputs/select.js
- src/gm3/util.js
Select boxes were making scary errors appear and freezing the application when there were no layers available.
> Fix scary errors when no selectable layers are available.

- src/gm3/actionTypes.js
- src/gm3/actions/map.js
- src/gm3/components/map/index.js
- src/gm3/reducers/cursor.js
- src/gm3/trackers/hash.js
- tests/gm3/trackers/hash.test.js
Allow passing in more location formats:
A. `zxy` - the default GeoMoose format since 3.0.
This is really `map resoltion;center x;center y`.
B. `lonlat` - Which is formatted as `zoom/lon/lat`.
C. `bbox` - Formatted as `west;south;east;north`. In ESPG:4326.
Adds the ability to change the hash emit format as well using
the new option for the HashTracker class. In `app.js`:
```
var hash_tracker = new gm3.trackers.HashTracker(app.store, {
locationFormat: 'lonlat'
});
```
> Add Bounding Box and Z/Lon/Lat support to loc param

- docs/howto/customize-results.rst
- examples/desktop/app.js
- src/gm3/application.js
- src/gm3/components/grid.js
- src/gm3/components/serviceManager.js
- src/gm3/lang/en.json
- src/gm3/lang/es.json
- src/gm3/lang/fr.json
- src/gm3/lang/it.json
- src/gm3/lang/pt-br.json
- src/less/results.less
- src/services/search.js
Adds a new "Buffer All" tool to the Super Tab results
when configured.
Bonus! Fixes bug with buffer-select not showing grid
results.
> Add "Buffer All" functionality

- .github/workflows/irc_notify.yml
- recent turmoil on Freenode servers, most have moved to the community-based irc.libera.chat server
- the GitHub action `notify-irc` also now sets the default server to be irc.libera.chat (https://github.com/rectalogic/notify-irc/pull/4)
- this pull request sets the default server by name
> set IRC notification to irc.libera.chat server

- examples/desktop/mapbook.xml
- src/gm3/components/map/index.js
- Refactores the pixel-tolerance code to be less inline with
the query function.
- Changes the AGS query and the WFS query to both use
pixel-tolerance as defined in the source. (AGS defaults to 2 as before)
Refs: #601
> Consistently buffer point on line/point queries

- examples/desktop/app.js
- src/gm3/components/serviceManager.js
- src/gm3/defaults.js
1. Remove the results config from the demo app.
2. Put the default config in defaults.js
3. Ensure the global defaults are honoured along
with specific service overrides.
Refs: #655
> Clean up cruft from results config PR

- src/gm3/components/serviceForm.js
- src/gm3/components/serviceManager.js
- src/services/select.js
1. Put the keyboard shortcuts on the document instead
of on the form to make Escape and Enter work properly.
2. Fix state-up issue with `submit()` message.
refs: #632
> Restore keyboard short cuts for service form

- docs/howto/add-decluttering.rst
- src/gm3/components/map/layers/vector.js
To restore the declutter behaviour,
```
<map-source ...>
<config name="declutter">true</config>
...
</map-source>
```
refs: #650
> Remove forced declutter and move it to source config.

- src/gm3/components/editor/modal.js
While property changes were saved, when recalled they
would be undefined, making it difficult to determine
their rendered values. This change requires that all
defaults be set by the properties.
refs: #658
> Ensure default properties are saved to property

- src/gm3/components/map/index.js
New context controls were not aware of how to behave
with the the selection layer. This fixes that oversight.
refs: #653
> Fix modify-selection bug

- src/gm3/components/map/index.js
No longer assume that `query.selection` is defined.
refs: #668
> Add safety rails around the selection checks

- src/gm3/components/grid.js
Using `Intl` fixes both #663 and #378.
> Fix for non-english and null values in grid sort

- examples/desktop/app.js
- examples/desktop/mapbook-test-servers.xml
- src/gm3/application.js
- src/gm3/trackers/hash.js
- src/gm3/util.js
- tests/gm3/application.test.js
1. Add a `mapbooks` block to the configuration object.
2. Have `loadMapbooks()` check for a `mapbook=` query parameter.
3. Use the `mapbooks` if available or use the one specified in `'default'`.
Features some additional cleanups:
- Removes `reqwest` dependency in application.js.
- Adds ability to pass in fetch options (new `fetchOpts:` property)
- Allow passing in of XML string instead of parsed document.
- Update all tests to match.
- Clean up query parsing logic and put it into util.js
refs: #645
> Add a technique for multiple mapbooks

- docs/howto/start-at-extent.rst
- src/gm3/components/map/index.js
1. Fixed a startup-view bug with `zoomToExtent`.
2. Added documentation on how to start from an extent.
refs: #564
> Fix state bug with zoom to extent and document

- src/gm3/actions/mapSource.js
- src/gm3/components/editor/modal.js
This provides an enumerated type for editing.
```
...
<property type="select" label="Encoding" default="dec">
<option value="dec">Decimal</option>
<option value="oct">Octal</option>
<option value="hex">Hexadecimal</option>
</property>
...
```
refs: #47
> Add "select" type for property editors

- src/gm3/components/map/index.js
The results-list should have built for multiple layers instead
of just the first. This change converts the single layer check
to a loop.
Also, a fixed required to prevent issues with the `fs` module.
refs: #576, #577
> Fix for highlight bug when multiple layers are on

- src/gm3/components/map/index.js
Drawing tool refactoring broke the buffer all tool.
This adds a check to ensure that there is a valid draw
tool to activate on the map.
refs: #699
> Fix for broken buffer all

- examples/desktop/mapbook.xml
- src/gm3/components/print/printModal.js
1. Adds check to ensure min/maxresolution are in range when
specified.
2. Adds a check to ensure the legend has not been turned off in the
catalog.
refs: #706
> Fix print legend visibility issues

- src/gm3/components/map/index.js
A query should be able to query on zero layers, this
is how Geomoose supports completely custom query back-ends.
> Regression fix: allow zero-layer queries

- examples/desktop/app.js
- src/gm3/components/serviceInputs/text.js
- src/less/serviceForms.less
Allow the administrator to add either helper text (an example
below the input) or a HTML based placehodler to the service forms.
> Add placeholder and helper text to inputs

- src/gm3/actions/mapSource.js
The parser was treating undefined as `false` which
is the opposite of the desired behavior.
refs: #738
> Ensure that highlight defaults to true

- src/gm3/actions/query.js
- src/gm3/application.js
- src/gm3/components/serviceManager/index.js
- src/gm3/components/toolbar/button.js
- src/gm3/reducers/query.js
- tests/gm3/components/toolbar.test.js
- Allows for composing the reset actions in the action instead of throughout components/reducers.
- Fixes but where an autoGo service was using the wrong geometry when switching services.
- Consolidates the logic between the application.js API and the toolbar button API.
refs: #750
> Make startService async

- src/services/identify.js
Adds a geometry gatekeeper to Identify's query
method.
> Do not allow Identify without a geometry

- docs/howto/add-grid-to-search-and-identify.rst
- src/services/search.js
- src/services/select.js
Grid templates were making assumptions about the service name, this fixes that and honors the `alias` setting.
refs: #684
> Fix grid template references

- src/gm3/components/serviceForm.js
- src/gm3/components/serviceInputs/layersList.js
- src/gm3/components/serviceInputs/select.js
Fix a long standing bug with <select> boxes not properly setting their default values when an express default value was not set by the administrator.
refs: #776
> Fix default value settings for select boxes

- docs/howto/change-empty-message.rst
- src/gm3/actions/query.js
- src/gm3/components/serviceManager/empty.js
- src/gm3/components/serviceManager/index.js
- src/gm3/components/serviceManager/results.js
- src/gm3/reducers/config.js
- src/gm3/reducers/query.js
Somehow a default "empty" state was lost in the mix. This creates a new bespoke component for such.
> Add an empty state and notice to service manager

- src/gm3/components/serviceForm.js
Previous logic made the  brash assumption that the default value set by the admin would be in the list at all times.
refs: #794 #793
> Improved Select Defaults Logic (again)

- src/gm3/components/serviceManager/results.js
Previously, this was using `getHighlightResults` which would incorrectly count the `highlight=false` layers as filtered out.
refs: #749
> Ensure that the results renderer uses getQueryResults

- examples/desktop/templates/parcel-row.html
- src/gm3/components/grid/index.js
Parses the `<tr/>` and checks for any events set in the template.
This fixes issue #760
> Fix row events for virtualized table

- src/gm3/reducers/map.js
In the old reducer, `zoom` would be removed from the state when zooming by resolution. If `zoom` is set the map honors that first, causing a logic issue and the `resolution` to not be honored.
This sets `zoom = null` to prevent that logic issue.
refs: #813
> Fix broken location restoration

- examples/desktop/mapbook.xml
- examples/mobile/mapbook.xml
Needed for MapServer 7.6.4 map= validation.
(I really thought we already did this.)
> Update mapbook mapfile paths to avoid './'

- src/gm3/actions/map.js
- src/gm3/components/map/index.js
- src/gm3/reducers/map.js
- src/gm3/trackers/hash.js
By default, `zoomToExtent` will pad the extent by 15 pixels. This adds an option to prevent that padding from happening when the tracker reloads a bounding box.
refs: #823
> Prevent padding from creating a "zoom out" effect

- src/gm3/components/print/printModal.js
- If a legend is less than 8 pixels tall, its assumed to be a space holder.
- Check if the image is all the same color, if so, consider it empty as well and do not include it in the print.
refs: #819
> Clean up empty legends

- src/gm3/components/print/printModal.js
Fixing camel case variables got aggressive. This rights that wrong in the `image_data` case for print templates.
refs: #810
> Fix broken `image_data`

- docs/howto/style-the-toolbar.rst
The Mapsk.in URL now leads to an Indian Casino, so swapping it out for their GitHub URL instead. Also updating the FontAwesome URL just because.
> Fix URLs for webfont sources

- examples/desktop/mapbook.xml
- src/gm3/actions/mapSource.js
- src/gm3/application.js
- src/gm3/components/coordinate-display.js
- src/gm3/components/drawTool.js
- src/gm3/components/line-icon.js
- src/gm3/components/map/index.js
- src/gm3/components/map/layers/measure.js
- src/gm3/components/map/layers/vector.js
- src/gm3/components/measure/calc.js
- src/gm3/components/measure/colorize.js
- src/gm3/components/measure/index.js
- src/gm3/components/measure/unit.js
- src/gm3/components/point-icon.js
- src/gm3/components/polygon-icon.js
- src/gm3/components/serviceManager/index.js
- src/gm3/lang/en.json
- src/gm3/lang/es.json
- src/gm3/lang/fr.json
- src/gm3/lang/it.json
- src/gm3/lang/pt-br.json
- src/gm3/reducers/mapSource.js
- src/gm3/util.js
- src/less/serviceForms.less
The goal of this PR is to provide:
- ~~[ ] Hover interactions between the features on the map and the features in the measure list.~~ Went with better cartography instead of the hover interaction.
> Measure Tool Enhancements

- src/gm3/components/grid/filter-modal.js
Update to use `this.state.value` instead of the previous `min` and `max`.
refs: #835
> Fix for range filter modals

- examples/desktop/mapbook-test-servers.xml
The service at https://gis2.co.dakota.mn.us/arcgis/rest/services/DCGIS_OL_Transportation/MapServer/ was republished and all the IDs changed...
> Updated service ids for various broken AGS layers

- src/less/gm3.less
There's a typo in the background-color setting for buttons that ends up in the geomoose.css file when the GeoMoose package is built.
> Fix background-color typo in gm3.less

- src/gm3/application.js
This prevents the service from getting included in the URL for the user after the query has been executed.
refs: #831
> Ensure the query is cleared after startup

- src/gm3/actions/query.js
- src/gm3/components/serviceManager/results.js
- src/gm3/selectors/query.js
- Changes the return signature for filtered results to be grouped by path.
- Updates results of the super tab to use that selector for rendering HTML.
refs: #698
> Honor filtered results in the super tab

- src/gm3/actions/mapSource.js
- src/gm3/application.js
- src/gm3/reducers/mapSource.js
- Allow graceful failure on a bad mapsource name
- Give the user more information on the console regarding bad XML in the mapbook.
> Catch common mapbook issues with nicer errors

- src/gm3/selectors/query.js
This prevents features from being highlighted based on the _started_ service intsead of the _rendered_ service.
> Use the query.serviceName instead of serviceName for highlight

- src/gm3/actions/mapSource.js
- src/gm3/components/map/index.js
- src/gm3/components/print/printImage.js
- src/gm3/components/print/printModal.js
- src/gm3/lang/en.json
Adds a new prop to Map and PrintImage that can turn off the rendering of the selection layer.
refs: #745
> Allow the selection to be toggled off during print

- examples/mobile/mobile.js
This will display the hash in the url for users by default, making it easier to both swap and share locations from mobile.
refs: #886
> Default to enabling hash tracker on mobile

- src/gm3/actions/query.js
Fixes mobile issue with not jumping to the reuslts tab.
> Restore "new-results" ui hint
